### ISSUE TITLE
HW-4 & HW-5 Suggestions

### ISSUE THREAD

**Issue by afandul** [maksym-artemiev/js_bootcamp#7]
Use argument `_id` instead `Tag._id`: 
https://github.com/maksym-artemiev/js_bootcamp/blob/2cb64eca2b70315e83b14f9626b3b6aac0d723c6/api/routes/tags/controller.js#L16

Better use await operations in separate line passing it's result into next function call:
https://github.com/maksym-artemiev/js_bootcamp/blob/2cb64eca2b70315e83b14f9626b3b6aac0d723c6/api/routes/tags/router.js#L8

Better keep database name in uri:
https://github.com/maksym-artemiev/js_bootcamp/blob/2cb64eca2b70315e83b14f9626b3b6aac0d723c6/api/db/dbconnect.js#L7

Do not use then() for await operations:
https://github.com/maksym-artemiev/js_bootcamp/blob/2cb64eca2b70315e83b14f9626b3b6aac0d723c6/api/db/dbconnect.js#L9

Use more predictive and explanatory naming for properties:
https://github.com/maksym-artemiev/js_bootcamp/blob/2cb64eca2b70315e83b14f9626b3b6aac0d723c6/api/db/models/posts.js#L17

**Comment by maksym-artemiev** [comment]
I was fixed all issues from your comments, thank you.
